# 必要START
sso:
  url: https://sso-agent-uat.mli.com.tw
backend:
  url: http://localhost:8081
frontend:
  url: http://127.0.0.1:5500/confidential/confidential-frontend/login.html

keycloak:
  realm: MLIExternalRealm
  clientId: test
  public-client: false
  cors: true
  credentials:
    secret: zDMMBBO4ddLeYXnHp828kkby7eeN9yZy

  bearer-only: true
  security-constraints:
    - authRoles: default-roles-MLIExternalRealm
      securityCollections:
        - patterns:
            - /* # 需要登入的路徑
# 必要END

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081
  servlet:
    context-path: /