server:
  port: 8081
  servlet:
    context-path: /
keycloak:
  auth-server-url: http://localhost:8080/
  realm: MLIExternalRealm
  clientId: test # Ensure this matches your Keycloak client's `client_id`
  public-client: false
  cors: true
  credentials:
    secret: d4krdfaNRp4tZwR1ZQ2bMRBfVkEx0Bks

  bearer-only: true
  security-constraints:
    - authRoles: default-roles-MLIExternalRealm
      securityCollections:
        - patterns:
            - /* # The paths requiring admin access

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

# 自定義參數
sso:
  url: http://localhost:8080
backend:
  url: http://localhost:8081
frontend:
  url: http://127.0.0.1:5500/confidential/confidential-frontend/login.html