# 必要START
sso:
  url: http://localhost:8080
backend:
  url: http://localhost:8081
frontend:
  url: http://127.0.0.1:5500/confidential/confidential-frontend/login.html

keycloak:
  realm: demo
  clientId: demo-client
  public-client: false
  cors: true
  credentials:
    secret: your-client-secret-here

  bearer-only: true
  security-constraints:
    - authRoles: default-roles-demo
      securityCollections:
        - patterns:
            - /* # 需要登入的路徑
# 必要END

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081
  servlet:
    context-path: /