server:
  port: 8081
  servlet:
    context-path: /

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MLIExternalRealm
          jwk-set-uri: http://localhost:8080/realms/MLIExternalRealm/protocol/openid-connect/certs
  # Database configuration removed

keycloak:
  auth-server-url: http://localhost:8080/
  realm: MLIExternalRealm
  resource: client_id # Ensure this matches your Keycloak client's `client_id`
  public-client: false
  cors: true
  credentials:
    secret: ILrhid1S5brjy21p9k6a0NU3DXsOTfEa

  bearer-only: true
  security-constraints:
    - authRoles: default-roles-MLIExternalRealm
      securityCollections:
        - patterns:
            - /* # The paths requiring admin access

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
